Repository LemonFace0309/msmr, pull requests merged in 2021-04, with the labels that each got.

#112 Responsive resilience covid19 banner
  components/ResilienceResource/CovidBanner.js
  components/ResilienceResource/CovidBanner.module.css
  components/shared/TextAndPic.js
  components/shared/TextAndPic.module.css
  package-lock.json
Labels: bug

#114 Landing photo
  package-lock.json
  public/images/landing-phone.png
Labels: bug

#110 Resolve #106: Privacy and Terms pages
  components/Footer.js
  package-lock.json
  pages/privacy.js
  pages/terms.js
Labels: enhancement

#113 Updated readme.md
  README.md
  docs/images/about_screenshot.png
  docs/images/resilence_screenshot.png
Labels: documentation

#121 Social media hyperlinks
  components/Footer.js
  components/Landing.js
  package-lock.json
Labels: enhancement

#117 Footer
  components/Footer.js
  components/Landing.js
  components/Meta.js
  styles/Footer.module.css
Labels: enhancement

#120 Fix #101: Awkwards gaps
  components/Contact.js
  components/MaxResilience.js
  components/Research/OngoingProjects.js
  components/ResilienceResource/CovidBanner.js
  components/ResilienceResource/CovidBanner.module.css
  components/ResilienceResource/MindfulnessExercises.js
  components/ResilienceResource/MindfulnessExercises.module.css
  components/shared/Banner.module.css
  components/shared/Button.module.css
  components/shared/Card.js
  components/shared/TextAndPic.js
  components/shared/TextAndPic.module.css
  pages/research.js
  pages/resilience.js
  styles/Title.module.css
Labels: bug, enhancement

#122 Connected Research page with featured articles page
  components/Research/OngoingProjects.js
  components/Research/Publications.js
  components/shared/Button.js
  components/shared/Button.module.css
  components/shared/Card.js
  package-lock.json
  package.json
  pages/msmr-articles/[slug].js
  pages/msmr-articles/index.js
  styles/Article.module.css
Labels: enhancement

#123 Fixes #56: Twitter bug and bigger media
  components/Nav.js
  components/NewsAndMedia.js
  styles/Nav.module.css
  styles/Title.module.css
Labels: bug, enhancement

#126 Added meta tags, pulled from Strapi backend
  components/Landing.js
  components/Meta.js
  components/Research/OngoingProjects.js
  components/Research/Publications.js
  pages/about.js
  pages/msmr-articles/[slug].js
  pages/msmr-articles/index.js
  public/images/articles/featured-article.jpg
  public/images/articles/ongoing-project.jpg
  styles/globals.css
Labels: enhancement

#132 General Improvements
  components/AboutMSMR.js
  components/Articles.js
  components/Jumbotron.js
  components/Landing.js
  components/MaxResilience.js
  components/ResearchingResilience.js
  components/shared/Banner.js
  components/shared/Button.js
  pages/about.js
  pages/index.js
  pages/msmr-articles/[slug].js
  public/images/instagram/eight.jpg
  public/images/instagram/five.jpg
  public/images/instagram/four.jpg
  public/images/instagram/nine.jpg
  public/images/instagram/one.jpg
  public/images/instagram/seven.jpg
  public/images/instagram/six.jpg
  public/images/instagram/three.jpg
  public/images/instagram/two.jpg
  styles/globals.css
Labels: enhancement
